name: gen_flash_english_study
version: 1.0.0+1
publish_to: none
environment:
  sdk: ^3.7.2
description: English vocabulary learning app with swipeable flashcards
dependencies:
  cached_network_image: ^3.4.1
  connectivity_plus: ^6.0.5
  cupertino_icons: ^1.0.8
  dio: ^5.7.0
  equatable: ^2.0.7
  firebase_auth: ^5.3.2
  firebase_core: ^3.8.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  flutter_hooks: ^0.20.0
  flutter_riverpod: ^2.5.1
  freezed_annotation: ^2.4.4
  go_router: ^14.0.0
  hooks_riverpod: ^2.5.1
  http: ^1.4.0
  json_annotation: ^4.9.0
  logger: ^2.4.0
  riverpod_annotation: ^2.5.1
  shared_preferences: ^2.3.2
dev_dependencies:
  build_runner: ^2.4.13
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.7
  json_serializable: ^6.8.0
  pedantic_mono: ^1.30.3
  pubspec_dependency_sorter: ^1.0.5
  riverpod_generator: ^2.5.1
flutter:
  uses-material-design: true
  assets:
    - .env
